/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupVolumeContents implements BackupVolumeContentInterface
type FakeBackupVolumeContents struct {
	Fake *FakeKahuV1beta1
}

var backupvolumecontentsResource = schema.GroupVersionResource{Group: "kahu.io", Version: "v1beta1", Resource: "backupvolumecontents"}

var backupvolumecontentsKind = schema.GroupVersionKind{Group: "kahu.io", Version: "v1beta1", Kind: "BackupVolumeContent"}

// Get takes name of the backupVolumeContent, and returns the corresponding backupVolumeContent object, and an error if there is any.
func (c *FakeBackupVolumeContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.BackupVolumeContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(backupvolumecontentsResource, name), &v1beta1.BackupVolumeContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupVolumeContent), err
}

// List takes label and field selectors, and returns the list of BackupVolumeContents that match those selectors.
func (c *FakeBackupVolumeContents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.BackupVolumeContentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(backupvolumecontentsResource, backupvolumecontentsKind, opts), &v1beta1.BackupVolumeContentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.BackupVolumeContentList{ListMeta: obj.(*v1beta1.BackupVolumeContentList).ListMeta}
	for _, item := range obj.(*v1beta1.BackupVolumeContentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupVolumeContents.
func (c *FakeBackupVolumeContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(backupvolumecontentsResource, opts))
}

// Create takes the representation of a backupVolumeContent and creates it.  Returns the server's representation of the backupVolumeContent, and an error, if there is any.
func (c *FakeBackupVolumeContents) Create(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.CreateOptions) (result *v1beta1.BackupVolumeContent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(backupvolumecontentsResource, backupVolumeContent), &v1beta1.BackupVolumeContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupVolumeContent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupVolumeContents) UpdateStatus(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.UpdateOptions) (*v1beta1.BackupVolumeContent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(backupvolumecontentsResource, "status", backupVolumeContent), &v1beta1.BackupVolumeContent{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.BackupVolumeContent), err
}

// Delete takes name of the backupVolumeContent and deletes it. Returns an error if one occurs.
func (c *FakeBackupVolumeContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(backupvolumecontentsResource, name), &v1beta1.BackupVolumeContent{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupVolumeContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(backupvolumecontentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.BackupVolumeContentList{})
	return err
}
