apiVersion: v1
kind: ServiceAccount
metadata:
  name: kahu-backup-service-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kahu-backup-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kahu-backup-service
  name: backup-role
rules:
  - apiGroups: ["kahu.io"]
    resources: ["backups", "backups/status", "restores", "restores/status", "backuplocations", "providers", "volumebackupcontents", "volumebackupcontents/status", "volumerestorecontents", "volumerestorecontents/status"]
    verbs: ["get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: [ "*" ]
    resources: ["*"]
    verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kahu-backup-service
  name: backup-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backup-role
subjects:
  - kind: ServiceAccount
    name: kahu-backup-service-sa
    namespace: {{ .Values.global.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kahu-backup-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kahu-backup-service
spec:
  replicas: {{ .Values.backupService.replicaCount}}
  selector:
    matchLabels:
      app: kahu-backup-service
  template:
    metadata:
      labels:
        app: kahu-backup-service
    spec:
      serviceAccount: kahu-backup-service-sa
      containers:
        - image: {{ .Values.images.backup }}
          imagePullPolicy: {{ .Values.global.image.pullpolicy }}
          name: backup
          command: [ "/usr/local/bin/controllermanager" ]
      volumes:
        - hostPath:
            path: /var/log/
            type: Directory
          name: log
        - hostPath:
            path: /opt
            type: DirectoryOrCreate
          name: opt

---
apiVersion: v1
kind: Service
metadata:
  name: kahu-backup-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kahu-backup-service
spec:
  selector:
    app: kahu-backup-service