/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	scheme "github.com/soda-cdm/kahu/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackupVolumeContentsGetter has a method to return a BackupVolumeContentInterface.
// A group's client should implement this interface.
type BackupVolumeContentsGetter interface {
	BackupVolumeContents() BackupVolumeContentInterface
}

// BackupVolumeContentInterface has methods to work with BackupVolumeContent resources.
type BackupVolumeContentInterface interface {
	Create(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.CreateOptions) (*v1beta1.BackupVolumeContent, error)
	UpdateStatus(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.UpdateOptions) (*v1beta1.BackupVolumeContent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.BackupVolumeContent, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.BackupVolumeContentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	BackupVolumeContentExpansion
}

// backupVolumeContents implements BackupVolumeContentInterface
type backupVolumeContents struct {
	client rest.Interface
}

// newBackupVolumeContents returns a BackupVolumeContents
func newBackupVolumeContents(c *KahuV1beta1Client) *backupVolumeContents {
	return &backupVolumeContents{
		client: c.RESTClient(),
	}
}

// Get takes name of the backupVolumeContent, and returns the corresponding backupVolumeContent object, and an error if there is any.
func (c *backupVolumeContents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.BackupVolumeContent, err error) {
	result = &v1beta1.BackupVolumeContent{}
	err = c.client.Get().
		Resource("backupvolumecontents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackupVolumeContents that match those selectors.
func (c *backupVolumeContents) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.BackupVolumeContentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.BackupVolumeContentList{}
	err = c.client.Get().
		Resource("backupvolumecontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backupVolumeContents.
func (c *backupVolumeContents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("backupvolumecontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a backupVolumeContent and creates it.  Returns the server's representation of the backupVolumeContent, and an error, if there is any.
func (c *backupVolumeContents) Create(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.CreateOptions) (result *v1beta1.BackupVolumeContent, err error) {
	result = &v1beta1.BackupVolumeContent{}
	err = c.client.Post().
		Resource("backupvolumecontents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backupVolumeContent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *backupVolumeContents) UpdateStatus(ctx context.Context, backupVolumeContent *v1beta1.BackupVolumeContent, opts v1.UpdateOptions) (result *v1beta1.BackupVolumeContent, err error) {
	result = &v1beta1.BackupVolumeContent{}
	err = c.client.Put().
		Resource("backupvolumecontents").
		Name(backupVolumeContent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backupVolumeContent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the backupVolumeContent and deletes it. Returns an error if one occurs.
func (c *backupVolumeContents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("backupvolumecontents").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backupVolumeContents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("backupvolumecontents").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}
